<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${applicationName!""} - Analysis Summary</title>
    <style>
        :root {
            --pf-color-primary: #06c;
            --pf-color-bg: #f0f0f0;
            --pf-color-surface: #fff;
            --pf-color-text: #151515;
            --pf-color-text-secondary: #6a6e73;
            --pf-color-border: #d2d2d2;
            --pf-color-danger: #c9190b;
            --pf-color-warning: #f0ab00;
            --pf-color-success: #3e8635;
            --pf-color-info: #2b9af3;
        }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'RedHatText', 'Helvetica Neue', Arial, sans-serif;
            background-color: var(--pf-color-bg);
            color: var(--pf-color-text);
            line-height: 1.5;
        }
        .header {
            background-color: #151515;
            color: #fff;
            padding: 16px 32px;
        }
        .header h1 { font-size: 20px; font-weight: 400; }
        .container { max-width: 1200px; margin: 0 auto; padding: 24px; }
        .page-title { font-size: 24px; margin-bottom: 24px; }
        .card-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
            gap: 16px;
            margin-bottom: 32px;
        }
        .card {
            background: var(--pf-color-surface);
            border: 1px solid var(--pf-color-border);
            border-radius: 3px;
            padding: 24px;
            text-align: center;
        }
        .card .value { font-size: 36px; font-weight: 700; color: var(--pf-color-primary); }
        .card .label { font-size: 14px; color: var(--pf-color-text-secondary); margin-top: 4px; }
        .section { margin-bottom: 32px; }
        .section h2 {
            font-size: 18px;
            border-bottom: 2px solid var(--pf-color-primary);
            padding-bottom: 8px;
            margin-bottom: 16px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            background: var(--pf-color-surface);
            border: 1px solid var(--pf-color-border);
        }
        th, td { padding: 12px 16px; text-align: left; border-bottom: 1px solid var(--pf-color-border); }
        th { background-color: #f0f0f0; font-weight: 600; font-size: 14px; }
        td { font-size: 14px; }
        .tag {
            display: inline-block;
            background: #e7f1fa;
            color: var(--pf-color-primary);
            padding: 2px 10px;
            border-radius: 12px;
            font-size: 13px;
            margin: 2px 4px;
        }
        .tags-container { display: flex; flex-wrap: wrap; gap: 4px; }
        .footer {
            text-align: center;
            padding: 24px;
            color: var(--pf-color-text-secondary);
            font-size: 13px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Windup Analysis Report</h1>
    </div>
    <div class="container">
        <h1 class="page-title">${applicationName!""} - Analysis Summary</h1>

        <div class="card-grid">
            <div class="card">
                <div class="value">${summary.totalFiles}</div>
                <div class="label">Files Analyzed</div>
            </div>
            <div class="card">
                <div class="value">${summary.totalIncidents}</div>
                <div class="label">Total Incidents</div>
            </div>
            <div class="card">
                <div class="value">${summary.totalStoryPoints}</div>
                <div class="label">Story Points</div>
            </div>
        </div>

        <div class="section">
            <h2>Incidents by Severity</h2>
            <table>
                <thead>
                    <tr>
                        <th>Severity</th>
                        <th>Count</th>
                    </tr>
                </thead>
                <tbody>
                    <#list incidentsBySeverity?keys as severity>
                    <tr>
                        <td>${severity}</td>
                        <td>${incidentsBySeverity[severity]}</td>
                    </tr>
                    </#list>
                </tbody>
            </table>
        </div>

        <#if summary.technologyTags?has_content>
        <div class="section">
            <h2>Detected Technologies</h2>
            <div class="tags-container">
                <#list summary.technologyTags as tag>
                <span class="tag">${tag.name()}</span>
                </#list>
            </div>
        </div>
        </#if>
    </div>
    <div class="footer">
        Generated by Windup
    </div>
</body>
</html>
